Refactor AutoSDK container image Dockerfile

diff --git a/examples/quickstart/autosdk/Dockerfile b/examples/quickstart/autosdk/Dockerfile
--- a/examples/quickstart/autosdk/Dockerfile
+++ b/examples/quickstart/autosdk/Dockerfile
@@ -1,104 +1,89 @@
 ARG BASE_IMAGE=epicgames/wine-patched:10.20
-
-FROM ubuntu:latest AS gatherer
+FROM ${BASE_IMAGE} AS structure
 
 ARG MAJOR_VERSION=17
 ARG MSVC_VERSION=17.14
 ARG SDK_VERSION=10.0.26100
-ARG PACKAGES=""
+ARG PACKAGES=''
 
+# Install our required system packages
+USER root
 RUN --mount=type=cache,target=/var/cache/apt,sharing=locked --mount=type=cache,target=/var/lib/apt,sharing=locked \
 	apt-get update && \
 	apt-get install -y --no-install-recommends \
-		ca-certificates \
-        git \
-        msitools \
-        python3
+		git \
+		msitools \
+		python3
 
-# get msvc-wine
-RUN git clone https://github.com/mstorsjo/msvc-wine.git /home/ubuntu/msvc-wine
+# Clone the msvc-wine repository
+USER nonroot
+RUN git clone --depth=1 'https://github.com/mstorsjo/msvc-wine.git' /tmp/msvc-wine
+WORKDIR /tmp/msvc-wine
 
-WORKDIR /home/ubuntu/msvc-wine
+# Install the requested Visual Studio components/workloads
+RUN export VSDOWNLOAD='./vsdownload.py --cache ./cache --accept-license --skip-patch' && \
+	if [ "$PACKAGES" != '' ]; then \
+		$VSDOWNLOAD --dest ./downloaded $PACKAGES ; \
+	else \
+		export VERSION_ARGS='--major $MAJOR_VERSION --msvc-version $MSVC_VERSION --sdk-version $SDK_VERSION' && \
+		$VSDOWNLOAD --dest ./downloaded $VERSION_ARGS && \
+		$VSDOWNLOAD --dest ./downloaded-llvm --major $MAJOR_VERSION && \
+		$VSDOWNLOAD --dest ./downloaded $VERSION_ARGS Microsoft.Net.Component.4.6.2.SDK; \
+	fi
 
-RUN if [ "$PACKAGES" != "" ]; then \
-        ./vsdownload.py --dest ./downloaded --cache ./cache --accept-license --skip-patch $PACKAGES ; \
-    else \
-        ./vsdownload.py --dest ./downloaded --cache ./cache --accept-license --skip-patch --major $MAJOR_VERSION --msvc-version $MSVC_VERSION --sdk-version $SDK_VERSION && \
-        ./vsdownload.py --dest ./downloaded-llvm --cache ./cache --accept-license --skip-patch --major $MAJOR_VERSION && \
-        ./vsdownload.py --dest ./downloaded --cache ./cache --accept-license --skip-patch --major $MAJOR_VERSION --msvc-version $MSVC_VERSION --sdk-version $SDK_VERSION package Microsoft.Net.Component.4.6.2.SDK; \
-    fi
+# Create the AutoSDK directory structure
+ENV AUTOSDK_DIR=/tmp/AutoSDK/HostWin64/Win64
+RUN mkdir -p "$AUTOSDK_DIR"
+RUN mkdir -p "$AUTOSDK_DIR/DIA SDK"
 
-# prepare winsdksetup for next stage
-RUN file=`find ./cache/ -iname winsdksetup.exe -type f` && \
-    cp $file /home/ubuntu/winsdksetup.exe
+# Move the files for the Windows SDK into the AutoSDK structure
+RUN mv '/tmp/msvc-wine/downloaded/Windows Kits' "$AUTOSDK_DIR/Windows Kits"
 
-# extract netfxsdk files
-RUN cd /home/ubuntu/msvc-wine/cache/Microsoft.Net.4.6.2.SDK-4.6.1590.5 && \
-    msiextract ./sdk_tools462.msi && \
-    mv "./Program Files/Windows Kits/NETFXSDK" /home/ubuntu/
+# Move the files for LLVM into the AutoSDK structure
+RUN if [ "$PACKAGES" != '' ]; then \
+		mv '/tmp/msvc-wine/downloaded/VC/Tools/Llvm' "$AUTOSDK_DIR/LLVM"; \
+	else \
+		mv '/tmp/msvc-wine/downloaded-llvm/VC/Tools/Llvm' "$AUTOSDK_DIR/LLVM"; \
+	fi
 
-# create AutoSDK folder structure
-RUN mkdir -p /home/ubuntu/AutoSDK/HostWin64/Win64
+# Move the directories for MSVC and the DIA SDK into the AutoSDK structure
+RUN if [ "$MAJOR_VERSION" = '16' ]; then \
+		export VS_VERSION='VS2019'; \
+	elif [ "$MAJOR_VERSION" = '17' ]; then \
+		export VS_VERSION='VS2022'; \
+	elif [ "$MAJOR_VERSION" = '18' ]; then \
+		export VS_VERSION='VS2026'; \
+	else \
+		echo 'Error: a valid SDK version must be specified!'; \
+		exit 1; \
+	fi && \
+	mv '/tmp/msvc-wine/downloaded/VC/Tools/MSVC' "$AUTOSDK_DIR/$VS_VERSION" && \
+	mv '/tmp/msvc-wine/downloaded/DIA SDK' "$AUTOSDK_DIR/DIA SDK/$VS_VERSION"
 
-# copy folders into the AutoSDK structure
-WORKDIR /home/ubuntu/AutoSDK/HostWin64/Win64
-RUN mv "/home/ubuntu/msvc-wine/downloaded/Windows Kits" "./Windows Kits" && \
-    if [ "$PACKAGES" != "" ]; then \
-        mv "/home/ubuntu/msvc-wine/downloaded/VC/Tools/Llvm" "./LLVM"; \
-    else \
-        mv "/home/ubuntu/msvc-wine/downloaded-llvm/VC/Tools/Llvm" "./LLVM"; \
-    fi && \
-    mv "/home/ubuntu/NETFXSDK" "./Windows Kits/" && \
-    mkdir "./DIA SDK" && \
-    if [ "$MAJOR_VERSION" = "16" ]; then \
-        mv "/home/ubuntu/msvc-wine/downloaded/VC/Tools/MSVC" ./VS2019 && \
-        mv "/home/ubuntu/msvc-wine/downloaded/DIA SDK" "./DIA SDK/VS2019" ; \
-    elif [ "$MAJOR_VERSION" = "17" ]; then \
-        mv "/home/ubuntu/msvc-wine/downloaded/VC/Tools/MSVC" ./VS2022 && \
-        mv "/home/ubuntu/msvc-wine/downloaded/DIA SDK" "./DIA SDK/VS2022" ; \
-    elif [ "$MAJOR_VERSION" = "18" ]; then \
-        mv "/home/ubuntu/msvc-wine/downloaded/VC/Tools/MSVC" ./VS2026 && \
-        mv "/home/ubuntu/msvc-wine/downloaded/DIA SDK" "./DIA SDK/VS2026" ; \
-    else \
-        echo "No valid sdk version specified"; \
-    fi
+# Extract the files for the .NET Framework SDK and move them into the AutoSDK structure
+RUN cd /tmp/msvc-wine/cache/Microsoft.Net.4.6.2.SDK-4.6.1590.5 && \
+	msiextract ./sdk_tools462.msi && \
+	mv './Program Files/Windows Kits/NETFXSDK' "$AUTOSDK_DIR/Windows Kits/NETFXSDK"
 
-FROM ${BASE_IMAGE} AS installer
+# Locate the Windows SDK installer executable
+RUN FILE=`find ./cache/ -iname winsdksetup.exe -type f` && \
+	cp "$FILE" /tmp/winsdksetup.exe
 
-WORKDIR /home/ubuntu/
+# Extract the Debugging Tools for Windows installer MSI from the Windows SDK installer executable
+RUN cd /tmp && \
+	wine winsdksetup.exe /layout ./winsdk_extracted /quiet /ceip off /features OptionID.WindowsDesktopDebuggers && \
+	mv /tmp/winsdk_extracted/Installers /tmp/DebugTools
 
-# create AutoSDK folder structure
-RUN mkdir -p /home/ubuntu/AutoSDK/HostWin64/Win64
+# Extract the files for the Debugging Tools for Windows and copy them into the AutoSDK structure
+# (Note that we copy here rather than move, so we can merge the directory trees)
+RUN cd /tmp/DebugTools && \
+	msiextract './X64 Debuggers And Tools-x64_en-us.msi' && \
+	cd './Windows Kits' && \
+	cp -R * "$AUTOSDK_DIR/Windows Kits/"
 
-# Get Debugging Tools for Windows
-COPY --from=gatherer --chown=nonroot:nonroot ["/home/ubuntu/winsdksetup.exe", "./winsdksetup.exe"]
-RUN wine winsdksetup.exe /layout ./temp /quiet /ceip off /features OptionID.WindowsDesktopDebuggers && \
-    mv "./temp/Installers" "/home/ubuntu/DebugTools"
-
-FROM ubuntu:latest AS debug_tools_grabber
-
-RUN --mount=type=cache,target=/var/cache/apt,sharing=locked --mount=type=cache,target=/var/lib/apt,sharing=locked \
-    apt-get update && \
-    apt-get install -y --no-install-recommends \
-        msitools
-
-WORKDIR /home/ubuntu/
-
-# create AutoSDK folder structure
-RUN mkdir -p /home/ubuntu/AutoSDK/HostWin64/Win64
-
-# Extract Debugging Tools for Windows
-COPY --from=installer --chown=nonroot:nonroot ["/home/ubuntu/DebugTools", "./DebugTools"]
-WORKDIR /home/ubuntu/DebugTools
-RUN msiextract ./X64\ Debuggers\ And\ Tools-x64_en-us.msi && \
-    mv "./Windows Kits" "/home/ubuntu/AutoSDK/HostWin64/Win64/Windows Kits"
-
-# Stage 3
+# Copy the assembled AutoSDK files into a clean version of our Wine base image
 FROM ${BASE_IMAGE}
-
-WORKDIR $WINEPREFIX/drive_c
-COPY --from=gatherer --chown=nonroot:nonroot ["/home/ubuntu/AutoSDK", "./AutoSDK"]
-COPY --from=debug_tools_grabber --chown=nonroot:nonroot ["/home/ubuntu/AutoSDK", "./AutoSDK"]
+COPY --from=structure --chown=nonroot:nonroot /tmp/AutoSDK ${WINEPREFIX}/drive_c/AutoSDK
 
 ENV UE_SDKS_ROOT=C:/AutoSDK
 ENV WINEDEBUG=-all
